<?php

namespace Acme\Bundle\StareStoreBundle\Repository;

/**
 * CategoriaProductoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CategoriaProductoRepository extends \Doctrine\ORM\EntityRepository
{
}
