<?php

namespace Acme\Bundle\StareStoreBundle\Repository;

/**
 * DetalleCarritoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DetalleCarritoRepository extends \Doctrine\ORM\EntityRepository
{
}
